def Hello_World():
    print("Hello World!")

Hello_World()

#WE NEED ASSETS - X

#WE NEED CHARACTERS - X

#WE NEED FOOD STATES - X

#WE NEED MEW LOCALISATED - X

#WE NEED SLEEPING OBJECTS - X

#WE NEED FOOD OBJECTS - X

#WE NEED TOY OBJECTS - X

#WE NEED TO SPAWN A PET - X

#WE NEED TO ANAIMATE IT - X

#WE NEED SOUNDS - X

#WE NEED THREADS - X

#WE NEED TO HIDE EVERYTHING BESIDES THE MAIN APP IN THE BACKGROUND - X

#WE NEED TO MAKE FOR LINUX ARCH AND LINUX DEBIAN OSES - X